version: '3'

services:
  postgres:
    image: postgres:11.7-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pix
      POSTGRES_HOST_AUTH_METHOD: trust

  redis:
    image: redis:5.0.7-alpine
    ports:
      - "6379:6379"
