
version: '3'

services:
  api:
    image: pix/api:dev
    build: 
      dockerfile: ../docker/dockerfiles/Dockerfile.hapi
      context: ../api/
      target: dev
    volumes:
      - ../api:/code
      - .env:/code/.env 

  orga:
    build: 
      dockerfile: ../docker/dockerfiles/Dockerfile.ember
      context: ../orga
      target: dev
    image: pix/orga:dev
    command: npx ember serve --proxy http://api:3000

  admin:
    build: 
      dockerfile: ../docker/dockerfiles/Dockerfile.ember
      context: ../admin/
      target: dev
    image: pix/admin:dev
    command: npx ember serve --proxy http://api:3000

  certif:
    build: 
      dockerfile: ../docker/dockerfiles/Dockerfile.ember
      context: ../certif/
      target: dev
    image: pix/certif:dev
    command: npx ember serve --proxy http://api:3000

  mon-pix:
    image: pix/mon-pix:dev
    build: 
      dockerfile: ../docker/dockerfiles/Dockerfile.ember
      context: ../mon-pix/
      target: dev
    command: npx ember serve --proxy http://api:3000
