version: '3'

services:
  postgres:
    image: postgres:14.10-alpine
    container_name: pix-e2e-postgres
    environment:
      POSTGRES_DB: pix
      POSTGRES_HOST_AUTH_METHOD: trust

  redis:
    container_name: pix-e2e-redis
    image: redis:7.0.12-alpine

  cypress:
    container_name: pix-e2e-cypress
    user: node
    build:
      context: .
    env_file: ./env-api
    volumes:
      - ../..:/code
    working_dir: /code/high-level-tests/e2e
    depends_on:
      - orga
      - monpix

  orga:
    container_name: pix-e2e-orga
    user: node
    image: node:20.9.0
    command: npx ember serve --proxy http://api:3000
    volumes:
      - ../..:/code
    working_dir: /code/orga
    depends_on:
      - api

  monpix:
    container_name: pix-e2e-monpix
    user: node
    image: node:20.9.0
    command: npx ember serve --proxy http://api:3000
    volumes:
      - ../..:/code
    working_dir: /code/mon-pix
    depends_on:
      - api

  api:
    container_name: pix-e2e-api
    user: node
    image: node:20.9.0
    env_file: ./env-api
    command: npm run start:watch
    volumes:
      - ../..:/code
    working_dir: /code/api
    depends_on:
      - redis
      - postgres
