name: automerge check

on:
  pull_request:
    types:
      - labeled
      - unlabeled
  check_suite:
    types:
      - completed
  status:
    types:
      - success

permissions: {}

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: 1024pix/pix-actions/auto-merge@v0.1.4
        with:
          auto_merge_token: '${{ secrets.PIX_SERVICE_ACTIONS_TOKEN }}'
